import { WellBeingTopic } from "../types";

export const WELLBEING_TOPICS: WellBeingTopic[] = [
  {
    id: "noise",
    title: "🔊 [1] Transition Noise",
    englishTitle: "Classroom Noise during Transitions",
    emoji: "🔊",
    description: "Managing sudden classroom noise and structureless movement during predictable lesson shifts.",
    insight: "Primary classrooms often become noisy when transitions are unpredictable and movement lacks structure. Noise increases when instructions are unclear, movement starts too early, waiting time becomes long, or teacher attention becomes fragmented.",
    teacherHack: "Freeze → Countdown → Transition: 1) Raise hand or clap signal; 2) Wait silently; 3) Start a 5-second countdown; 4) Show visual instructions on the board; 5) Students move only after complete silence.",
    sources: [
      "National Education Policy (NEP) 2020 - Safe & Structured Learning Environments",
      "Harvard Center on the Developing Child - Executive Function & Self-Regulation in Classrooms "
    ],
    powerKeywords: ["Quiet clapping signal", "5-second countdown", "Visual board cues", "No shouting rules"]
  },
  {
    id: "burnout",
    title: "🔥 [2] Burnout Prevention",
    englishTitle: "Teacher Burnout and Exhaustion",
    emoji: "🔥",
    description: "Detecting emotional exhaustion warning signs, exhaustion fatigue, and workload control.",
    insight: "Teacher burnout usually begins through emotional exhaustion rather than dramatic breakdowns. It increases when teachers multitask continuously, carry school stress home, remain available after school hours, or never mentally recover.",
    teacherHack: "The 90-Second Reset: Use a somatic transition pause after every 2 classes (Deep breathing, hydration, shoulder relaxation, silent pause). Protect one 'no school discussion hour' daily after work.",
    sources: [
      "World Health Organization (WHO) - ICD-11 Burnout Syndrome Diagnostic Directives",
      "NIMHANS India - Cognitive Stress-Decompression Frameworks for School Teachers"
    ],
    powerKeywords: ["90-second breathing pause", "No-WhatsApp offline boundary", "Work-home segregation", "Energy triage checklists"]
  },
  {
    id: "emotional",
    title: "🧘 [3] Post-Conflict Calm",
    englishTitle: "Emotional Regulation after Conflict",
    emoji: "🧘",
    description: "Managing stressful triggers, somatic self-soothing, and modeling quiet classroom dialogue.",
    insight: "Teachers often carry emotional tension from one difficult class into the next. This affects voice tone, patience, and classroom energy. Common triggers: repeated interruptions, disrespectful behavior, shouting, peer conflict, refusal to follow instructions.",
    teacherHack: "Somatic Grounded Reset: Never attempt emotional correction while emotionally activated. Use a deliberate pause before speaking, lower your voice speed and volume, and maintain still body posture. Do deep breathing, relax shoulders, and drink water.",
    sources: [
      "Yale Center for Emotional Intelligence - The RULER Socio-Emotional Learning Methodology",
      "UNICEF India wellbeing toolkits - Stress Mitigation & Co-Regulation guides"
    ],
    powerKeywords: ["Slience-first boundaries", "Restorative voice modulation", "Releasing neck & shoulder stress", "Trigger observation diary"]
  },
  {
    id: "parents",
    title: "👥 [4] Parent Stress",
    englishTitle: "Teacher Stress from Parent Expectations",
    emoji: "👥",
    description: "Creating professional templates for communication and academic pressure boundary solutions.",
    insight: "Teachers often experience emotional pressure from parents who expect constant academic perfection. Stress increases when parents compare children, late-night messaging becomes frequent, or emotional conversations happen without preparation.",
    teacherHack: "Structured Communication Templates: Reply with neutral, constructive boundaries: 'Thank you for sharing your concern. I will observe this closely and update you with specific observations.' Avoid defensive replies or instant reactions.",
    sources: [
      "School-Family Partnerships & Educator Wellness Studies",
      "Indian Multilingual Primary Parent Communications Handbook"
    ],
    powerKeywords: ["Standardized response templates", "Pre-meeting preparation checklist", "Off-duty notification frames", "Calm vocal speed drills"]
  },
  {
    id: "motivation",
    title: "🌊 [5] PERMA Motivation",
    englishTitle: "PERMA Meaning and Teacher Motivation",
    emoji: "🌊",
    description: "Reconnecting with teaching purpose, Seligman's science of flourishing, and classroom flow.",
    insight: "Many teachers lose connection with meaning before they lose energy. Teaching starts feeling mechanical instead of purposeful. The 'Meaning' part of the PERMA model focuses on purpose, contribution, and impact.",
    teacherHack: "The Meaning Journal: Note once a week: 1 student success moment, 1 positive emotional connection, and 1 meaningful classroom interaction. Ask yourself: 'Why did I originally choose teaching?' regularly.",
    sources: [
      "Martin Seligman's Positive Psychology Center, University of Pennsylvania",
      "WHO Indian Regional Mental Well-Being Pedagogical Toolkits"
    ],
    powerKeywords: ["Meaning journal tracker", "Small effort celebration card", "Fostering child autonomy", "Original intent check-in"]
  },
  {
    id: "attention",
    title: "⚡ [6] Student Attention",
    englishTitle: "Student Attention Loss",
    emoji: "⚡",
    description: "Structuring active lesson resets to maintain focus and attention anchoring.",
    insight: "Middle school students lose attention rapidly when passive listening exceeds their regulation capacity. Common causes: long lectures, low movement, low participation, unclear relevance.",
    teacherHack: "7-Minute Engagement Reset: Include a brief cooperative question, 1-minute partner discuss prompt, movement cue, or quick challenge every 7 minutes. Use student names frequently as focus anchors.",
    sources: [
      "Cognitive Educational Engagement Metrics - Adolescent Development Guides",
      "Neuroscience-Backed Active Engagement Frameworks in Modern Schools"
    ],
    powerKeywords: ["7-minute micro-breaks", "Name focus anchors", "Peer-led discussions", "Tactile learning intervals"]
  },
  {
    id: "perfectionism",
    title: "🎯 [7] Stress & Perfection",
    englishTitle: "Teacher Anxiety and Perfectionism",
    emoji: "🎯",
    description: "Releasing over-preparation habits and building realistic 'good enough' classrooms.",
    insight: "Teacher anxiety frequently appears as over-preparation, perfectionism, and fear of losing classroom control. This triggers overexplaining, emotional irritation, and the inability to let go.",
    teacherHack: "Good Enough Teaching Rules: Ask daily: 1) Did students feel safe? 2) Did learning happen? 3) Was perfection actually necessary? Schedule one low-pressure lesson weekly where mistakes are celebrated.",
    sources: [
      "Anxiety & Educator Support Frameworks - Clinical Wellness Handbooks",
      "Indian Council of Mindful Education - Anti-Perfectionist Lesson Planning Standards"
    ],
    powerKeywords: ["Good Enough Classroom Standards", "Low-pressure test zones", "Delegating monitoring roles to kids", "Overprep triage plans"]
  },
  {
    id: "overstimulation",
    title: "🍭 [8] Room Overstimulation",
    englishTitle: "Primary Classroom Overstimulation",
    emoji: "🍭",
    description: "De-escalating sensory overload, impulsive noise levels, and hyperactivity.",
    insight: "Primary students become overstimulated when movement, sound, visual input, and instructions happen simultaneously, causing impulsive behavior, shouting, and listening failure.",
    teacherHack: "Input Reduction: Deliver one instruction at a time, support spoken directives with simple diagrams on the board, keep a calm tone, and construct a dedicated classroom quiet reset corner.",
    sources: [
      "Early Childhood Sensory Management Classrooms",
      "Socio-Emotional Sensory Integration and De-escalation Research"
    ],
    powerKeywords: ["Single-instruction pacing", "Visual blackboard support", "Cozy quiet classroom corners", "Deep quiet reset checks"]
  },
  {
    id: "recovery",
    title: "🌱 [9] Recovery & Rest",
    englishTitle: "Teacher Recovery and Resilience",
    emoji: "🌱",
    description: "Designing decompression routines after work to regulate the nervous system.",
    insight: "Recovery is not laziness. Recovery is emotional maintenance. Teachers who never recover gradually lose patience, creativity, emotional flexibility, and classroom presence.",
    teacherHack: "Decompression Rituals: Dedicate 15 minutes immediately after returning home to music, walking, or silence. Avoid discussing school stress or checking school WhatsApp groups during this buffer.",
    sources: [
      "Educator Resilience & Somatic Tension Regulation - Post-Work Studies",
      "Nervous System Recovery for High-Touch Professionals"
    ],
    powerKeywords: ["After-school buffer rituals", "No-school talk slots", "Somatic stretching checks", "Digital-free wellness minutes"]
  }
];

// Multilingual translations and localized prompts
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  English: {
    welcome: "Welcome Teacher Saathi! I am your companion for socio-emotional well-being.",
    detecting: "Detecting your regional location...",
    detected: "We detected your region as",
    andLanguage: "and spoken language as",
    correct: "Is this correct?",
    confirm: "Yes, Continue",
    change: "Change Language/Region",
    onboardingTitle: "Introduce Yourself",
    name: "Full Name",
    namePlaceholder: "Enter your name...",
    classTaught: "Which Grade/Class do you teach?",
    experience: "Years of Teaching Experience",
    phone: "Phone Number (Optional)",
    email: "Email Address (Optional)",
    submit: "Get Started",
    placeholderChat: "Ask your wellbeing doubt or click a topic button...",
    multiSelectWarn: "Aap ek saath multiple topics select kar sakte hain (e.g., 1, 3).",
    more: "more....",
    less: "show less",
    changeLangTitle: "Choose Language & Region",
    escalatePrompt: "Bilkul, an expert mentor will contact you soon. Please share your phone/email if not done.",
    escalatedText: "I've noted these for our expert.",
    endText: "Aapse baat karke khushi hui. Khush rahiye! Goodbye!",
    endBlockTitle: "Chat Session Completed",
    endBlockSub: "Thank you for dedicating your time to classroom happiness.",
    restart: "Start New Session",
    nudgeText: "Hi Teacher! Are you there? Let's discuss our wellbeing topic today. 😊",
    warningText: "You have been inactive. We will close our chat in 5 minutes to save resources. Click 'Stay' to continue!",
    stayBtn: "Stay",
    adminTitle: "Labhya Admin Analytics Portal",
    teacherIndex: "School Educators",
    analyticsLogs: "System Events & Analytics Logs",
    chatTraces: "AI Chat Transcripts",
    backToChat: "Return to Chat UI",
    adminDesc: "Real-time records saved programmatically on our server-side JSON database."
  },
  Hindi: {
    welcome: "नमस्ते शिक्षक साथी! मैं सामाजिक-भावनात्मक कल्याण के लिए आपकी मार्गदर्शक हूँ।",
    detecting: "आपकी भौगोलिक स्थिति का पता लगाया जा रहा है...",
    detected: "हमने आपकी क्षेत्र स्थिति का पता लगाया:",
    andLanguage: "और आपकी प्राथमिक भाषा:",
    correct: "क्या यह जानकारी सही है?",
    confirm: "हाँ, आगे बढ़ें",
    change: "भाषा/क्षेत्र बदलें",
    onboardingTitle: "अपना परिचय दें",
    name: "पूरा नाम",
    namePlaceholder: "अपना नाम दर्ज करें...",
    classTaught: "आप किस कक्षा/ग्रेड को पढ़ाते हैं?",
    experience: "शिक्षण का कुल अनुभव",
    phone: "फ़ोन नंबर (वैयक्तिक)",
    email: "ईमेल आईडी (वैयक्तिक)",
    submit: "शुरू करें",
    placeholderChat: "अपनी शंका पूछें या नीचे दिए गए किसी विषय पर क्लिक करें...",
    multiSelectWarn: "आप एक साथ कई विषयों को चुन सकते हैं (उदा. 1, 3)।",
    more: "विस्तार से देखें....",
    less: "कम दिखाएं",
    changeLangTitle: "भाषा और क्षेत्र चुनें",
    escalatePrompt: "बिल्कुल, एक विशेषज्ञ मेंटर जल्द ही आपसे संपर्क करेंगे। यदि आपने अपना फ़ोन/ईमेल साझा नहीं किया है, तो कृपया यहाँ साझा करें।",
    escalatedText: "मैंने इन्हें हमारे विशेषज्ञ के लिए नोट कर लिया है।",
    endText: "आपसे बात करके खुशी हुई। खुश रहिए! अलविदा!",
    endBlockTitle: "बातचीत समाप्त हुई",
    endBlockSub: "कक्षा की खुशहाली के लिए अपना अमूल्य समय देने के लिए धन्यवाद।",
    restart: "नया सत्र शुरू करें",
    nudgeText: "नमस्ते शिक्षक साथी! क्या आप वहाँ हैं? आज हमारे खुशहाली विषय पर चर्चा जारी रखें। 😊",
    warningText: "आप निष्क्रिय हैं। ऊर्जा बचाने के लिए हम 5 मिनट में चैट बंद कर देंगे। जारी रखने के लिए 'बने रहें' पर क्लिक करें!",
    stayBtn: "बने रहें",
    adminTitle: "लभ्य एडमिन एनालिटिक्स पोर्टल",
    teacherIndex: "स्कूल शिक्षक रिकॉर्ड",
    analyticsLogs: "सिस्टम इवेंट और एनालिटिक्स लॉग",
    chatTraces: "AI चैट ट्रांसक्रिप्ट",
    backToChat: "चैट पर वापस जाएं",
    adminDesc: "हमारे सर्वर-साइड JSON डेटाबेस पर सहेजे गए वास्तविक समय के रिकॉर्ड।"
  },
  Bengali: {
    welcome: "স্বাগতম শিক্ষক সাথী! আমি সামাজিক-আবেগীয় সুস্থতার জন্য আপনার পরামর্শদাতা।",
    detecting: "আপনার ভৌগোলিক অবস্থান অনুসন্ধান করা হচ্ছে...",
    detected: "আমরা সনাক্ত করেছি আপনার রাজ্য:",
    andLanguage: "এবং আপনার ভাষা:",
    correct: "এটি কি সঠিক?",
    confirm: "হ্যাঁ, এগিয়ে যান",
    change: "ভাষা/রাজ্য পরিবর্তন করুন",
    onboardingTitle: "আপনার পরিচয় দিন",
    name: "আপনার নাম",
    namePlaceholder: "আপনার সম্পূর্ণ নাম লিখুন...",
    classTaught: "আপনি কোন ক্লাসের শিক্ষক?",
    experience: "মোট শিক্ষাদান অভিজ্ঞতা (বছর)",
    phone: "ফোন নম্বর (ঐচ্ছিক)",
    email: "ইমেল আইডি (ঐচ্ছিক)",
    submit: "শুরু করুন",
    placeholderChat: "আপনার প্রশ্ন টাইপ করুন বা নিচের বিষয়গুলোর ওপর ক্লিক করুন...",
    multiSelectWarn: "আপনি একসাথে একাধিক বিষয় নির্বাচন করতে পারেন (যেমন ১, ৩)।",
    more: "আরো পড়ুন....",
    less: "কম দেখান",
    changeLangTitle: "ভাষা এবং রাজ্য নির্বাচন করুন",
    escalatePrompt: "অবশ্যই, আমাদের একজন বিশেষজ্ঞ মেন্টর শীঘ্রই আপনার সাথে যোগাযোগ করবেন। আপনার ফোন বা ইমেল দিয়ে রাখুন যাতে আমরা খুঁজে পাই।",
    escalatedText: "আমি আমাদের বিশেষজ্ঞের জন্য এগুলো লিখে রেখেছি।",
    endText: "আপনার সাথে কথা বলে আনন্দিত হলাম। খুশী থাকুন! বিদায়!",
    endBlockTitle: "চ্যাট সেশন শেষ হয়েছে",
    endBlockSub: "শ্রেণীকক্ষের খুশির জন্য আপনার মূল্যবান সময় দেওয়ার জন্য ধন্যবাদ।",
    restart: "নতুন সেশন শুরু করুন",
    nudgeText: "হ্যালো শিক্ষক সাথী! আপনি কি আছেন? চলুন আজ আমাদের সুস্থতার বিষয় নিয়ে আলোচনা করি। 😊",
    warningText: "আপনি নিষ্ক্রিয় আছেন। সেশন বন্ধ হতে ৫ মিনিট বাকি। চালু রাখতে 'থাকুন' ক্লিক করুন!",
    stayBtn: "থাকুন",
    adminTitle: "লভ্য অ্যাডমিন অ্যানালিটিক্স",
    teacherIndex: "শিক্ষক সূচক",
    analyticsLogs: "সিস্টেম ইভেন্ট ও অ্যানালিটিক্স লগ",
    chatTraces: "AI চ্যাট ট্রান্সক্রিপ্ট",
    backToChat: "চ্যাটে ফিরে যান",
    adminDesc: "আমাদের সার্ভার-সাইড JSON ডাটাবেসে রিয়েল-টাইমে সংরক্ষিত রেকর্ডসমুহ।"
  },
  Gujarati: {
    welcome: "સ્વાગત છે શિક્ષક સાથી! હું આપના સામાજિક-ભાવનાત્મક કલ્યાણ માટે આપની માર્ગદર્શક છું.",
    detecting: "આપની ભૌગોલિક સ્થિતિ જાણી રહ્યા છીએ...",
    detected: "અમે આપનું રાજ્ય આ શોધી કાઢ્યું છે:",
    andLanguage: "અને આપની મુખ્ય ભાષા:",
    correct: "શું આ માહિતી સાચી છે?",
    confirm: "હા, આગળ વધો",
    change: "ભાષા અથવા રાજ્ય બદલો",
    onboardingTitle: "આપનો પરિચય આપો",
    name: "આપણું નામ",
    namePlaceholder: "આપનું પૂરું નામ લખો...",
    classTaught: "આપ કયો ધોરણ ભણાવો છો?",
    experience: "શિક્ષણનો અનુભવ (વર્ષો)",
    phone: "ફોન નંબર (વૈકલ્પિક)",
    email: "ઈમેલ આઈડી (વૈકલ્પિક)",
    submit: "શરૂ કરો",
    placeholderChat: "આપની શંકાઓ પૂછો અથવા નીચેના કોઈપણ વિષય પર ક્લિક કરો...",
    multiSelectWarn: "આપ એક સાથે અનેક વિષયો પસંદ કરી શકો છો (દા.ત., 1, 3).",
    more: "વધુ વિગતો જુઓ....",
    less: "ઓછું બતાવો",
    changeLangTitle: "ભાષા અને રાજ્ય પસંદ કરો",
    escalatePrompt: "ચોક્કસ, અમારા નિષ્ણાત મેન્ટર ટૂંક સમયમાં આપનો સંપર્ક કરશે. જો ફોન અથવા ઈમેલ વિગત નથી આપી તો કૃપા કરીને અહીં આપો.",
    escalatedText: "મેં આ માહિતી અમારા નિષ્ણાત માટે નોંધી લીધી છે.",
    endText: "આપની સાથે વાત કરીને ખૂબ આનંદ થયો. ખુશ રહો! આવજો!",
    endBlockTitle: "વાતચીત પૂર્ણ થઈ",
    endBlockSub: "વર્ગખંડની ખુશાલી માટે આપનો અમૂલ્ય સમય આપવા બદલ આભાર.",
    restart: "નવું સત્ર શરૂ કરો",
    nudgeText: "નમસ્તે શિક્ષક સાથી! આપ હાજર છો? ચાલો આજે આપણા વિષય પર ચર્ચા ચાલુ રાખીએ. 😊",
    warningText: "આપ નિષ્ક્રિય છો. ઊર્જા બચાવવા 5 મિનિટમાં આ ચેટ બંધ કરી દીધામાં આવશે. ચાલુ રાખવા 'જોડાયેલા રહો' પર ક્લિક કરો!",
    stayBtn: "જોડાયેલા રહો",
    adminTitle: "લભ્ય એડમિન એનાલિટિક્સ",
    teacherIndex: "શિક્ષકોનું રજિસ્ટર",
    analyticsLogs: "સિસ્ટમ એનાલિટિક્સ લોગ્સ",
    chatTraces: "AI ચેટ ટ્રાન્સક્રિપ્ટ્સ",
    backToChat: "ચેટ પર પાછા ફરો",
    adminDesc: "સર્વર-સાઇડ JSON ડેટાબેઝ પર સુરક્ષિત રીતે સંગ્રહિત થયેલ લાઇવ રેકોર્ડ્સ."
  },
  Hinglish: {
    welcome: "Welcome Teacher Saathi! Main socio-emotional well-being ke liye aapki Indian female mentor hoon.",
    detecting: "Somatic check... Aapki device location detect kar rahe hain...",
    detected: "Humne aapka primary state detect kiya hai:",
    andLanguage: "aur spoken language:",
    correct: "Kya ye details bilkul sahi hain?",
    confirm: "Haan, Continue karein",
    change: "Language/State Change karein",
    onboardingTitle: "Apni basic details share karein",
    name: "Full Name",
    namePlaceholder: "Apna naam likhein...",
    classTaught: "Aap kaunsi class ko teach karte hain?",
    experience: "Years of Teaching Experience?",
    phone: "Phone Number (Expert call ke liye)",
    email: "Email Address (Optional)",
    submit: "Ready, Start karein",
    placeholderChat: "Apna wellbeing doubt puchhein ya direct topic click karein...",
    multiSelectWarn: "Aap ek saath multiple topics select kar sakte hain (e.g., 1, 3).",
    more: "more....",
    less: "show less",
    changeLangTitle: "Language aur State manual select karein",
    escalatePrompt: "Bilkul, an expert mentor will contact you soon. Please share your phone/email if not done.",
    escalatedText: "I've noted these for our expert.",
    endText: "Aapse baat karke khushi hui. Khush rahiye! Goodbye!",
    endBlockTitle: "Chat Session Finised",
    endBlockSub: "Aapke classroom ki happiness boost karne ke liye supportive thank you.",
    restart: "Starting Another session",
    nudgeText: "Hi Teacher! Are you there? Let's discuss our wellbeing topic today. 😊",
    warningText: "Aap kafi der se inactive hain. Resource save karne ke liye hum chat 5 minutes me end kar denge. Click 'Stay' to continue!",
    stayBtn: "Stay",
    adminTitle: "Labhya Admin Analytics Terminal",
    teacherIndex: "Educator Directories",
    analyticsLogs: "System Telemetry & Access Logs",
    chatTraces: "AI Conversation Transcripts",
    backToChat: "Go back to Chat Interface",
    adminDesc: "Database engine logs stored securely inside our micro-services json file."
  }
};
